language: java
jdk:
  - oraclejdk8
# command to run tests
script:
 - coverage run -m java /home/travis/build/ssw-695-spring-2021-group-afjk/sttTinker.java
after_success:
 - bash <(curl -s https://codecov.io/bash)
